name: rl-lab
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10

  # Core ML/Scientific Computing (CPU-only)
  - pytorch-cpu>=2.0.0
  - torchvision-cpu
  - torchaudio-cpu
  - numpy>=1.24.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0

  # Data handling and visualization
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pillow>=10.0.0
  - imageio>=2.31.0

  # Configuration and utilities
  - pyyaml>=6.0
  - tqdm>=4.65.0

  # Development tools
  - pytest>=7.3.0
  - black>=23.3.0
  - flake8>=6.0.0
  - mypy>=1.4.0
  - jupyterlab

  # System utilities
  - git

  # Pip for packages not available in conda
  - pip

  # Packages that must be installed via pip
  - pip:
    # RL Environments
    - gymnasium>=0.28.0
    - dm-control>=1.0.14
    
    # Logging and monitoring
    - tensorboard>=2.13.0
    - wandb>=0.15.0
    
    # Configuration management  
    - hydra-core>=1.3.0
    
    # Hyperparameter optimization
    - optuna>=3.2.0
    
    # Additional utilities
    - opencv-python>=4.8.0
    
    # Optional environment dependencies
    # - atari-py>=0.2.9              # For Atari environments
    # - mujoco>=2.3.0                # For MuJoCo environments  
    # - box2d-py>=2.3.5              # For Box2D environments
    # - pybullet>=3.2.5              # For PyBullet environments

# Notes for Linux CPU-only:
# 1. Uses CPU-only PyTorch variants for smaller download and no CUDA dependencies
# 2. Good for CI/CD, servers without GPUs, or development/testing
# 3. Training will be slower than GPU versions but all functionality is preserved
# 4. Some RL environments may require additional system packages