name: rl-lab
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core Python
  - python=3.10

  # Core ML/Scientific Computing (optimized for Apple Silicon)
  - pytorch>=2.0.0
  - torchvision
  # PyTorch automatically uses MPS (Metal Performance Shaders) on Apple Silicon
  - numpy>=1.24.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0

  # Data handling and visualization (plotting via TensorBoard/WandB)
  - pandas>=2.0.0
  - seaborn>=0.12.0
  - pillow>=10.0.0
  - imageio>=2.31.0

  # Configuration and utilities
  - pyyaml>=6.0
  - tqdm>=4.65.0

  # Development tools
  - pytest>=7.3.0
  - black>=23.3.0
  - flake8>=6.0.0
  - mypy>=1.4.0
  - jupyterlab

  # Git and version control
  - git

  # Pip for packages not available in conda
  - pip

  # Packages that must be installed via pip
  - pip:
    # RL Environments
    - gymnasium>=0.28.0
    - dm-control>=1.0.14
    
    # Logging and monitoring
    - tensorboard>=2.13.0
    - wandb>=0.15.0
    
    # Configuration management  
    - hydra-core>=1.3.0
    
    # Hyperparameter optimization
    - optuna>=3.2.0
    
    # Additional utilities
    - opencv-python>=4.8.0
    
    # macOS-specific optimizations
    - psutil>=5.9.0  # Better system monitoring on macOS

# Notes for macOS/Apple Silicon:
# 1. No CUDA dependencies (not supported on Apple Silicon)
# 2. PyTorch will automatically use MPS acceleration when available
# 3. Some packages may need Rosetta 2 for Intel compatibility
# 4. For better performance, ensure you're using native ARM64 packages